export const ComponentIDs = {
  basicNavbarNav: 'basicNavbarNav',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  filterMenuItem: 'filterMenuItem',
  homeFormFirstName: 'homeFormFirstName',
  homeFormLastName: 'homeFormLastName',
  homeFormBio: 'homeFormBio',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',
  interestsMenuItem: 'interestsMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  profilesMenuItem: 'profilesMenuItem',
  projectsMenuItem: 'projectsMenuItem',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormSubmit: 'signUpFormSubmit',
  recipelistMenuItem: 'recipelistMenuItem',
  updateProfileMenuItem: 'updateProfileMenuItem',
  recipelistMenuItemAdmin: 'recipelistMenuItemAdmin',
};

export const PageIDs = {
  filterPage: 'filterPage',
  homePage: 'homePage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  profilesPage: 'profilesPage',
  projectsPage: 'projectsPage',
  recipesListPage: 'recipesListPage',
  recipeListPageAdmin: 'recipeListPageAdmin',
  recipePage: 'recipePage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
  updateProfilePage: 'updateProfilePage',
};
